config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  resources :books
  root 'books#home'
  get 'home/about' => 'books#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def current_user?(user)
    current_user.id == user.id
  end
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, length: {in: 2..20 }
  validates :introduction, length: {maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
  def after_sign_in_path_for(resource)
      user_path(current_user)
  end

  def after_sign_out_path_for(resource)
      root_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit]
  before_action :correct_user, only: [:edit, :update]
  def index
      @books = Book.all
      @book = Book.new
      @user = current_user
  end

  def show
      @books = Book.find(params[:id])
      @book = Book.new
      @user = @books.user
  end

  def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
     if @book.save
        redirect_to book_path(@book.id)
        flash[:notice] = 'Book was successfully created.'
     else
     	@user = current_user
        @books = Book.all
        render :index
     end
  end

  def new
      @book = Book.new
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
      @book = Book.find(params[:id])
     if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = 'Book was successfully updated.'
     else
      render :edit
     end
  end

  def destroy
      @books = Book.find(params[:id])
      @books.destroy
      redirect_to books_path
  end

 private
  def book_params
      params.require(:book).permit(:title, :body)
  end
  def correct_user
    book = Book.find(params[:id])
    if current_user != book.user
      redirect_to books_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  def show
      @users = User.find(params[:id])
      @book = Book.new
      @books = @users.books
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])
     if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = 'Book was successfully updated.'
     else
      render :edit
     end

  end

  def index
      @users = User.all
      @book = Book.new
      @user = current_user
  end

 private
  def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
  end
   def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>

<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:"100x100" %>
<table class="table table-condensed">
<tr>
<th>name</th>
<td><%= user.name %></td></tr>
<tr>
<th>introduction</th>
<td><%= user.introduction %></td></tr>
</table>
<% if user == current_user %>
<%= link_to(edit_user_path(user.id)) do %>
<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
<% end %>
<% end %>

<h2>New book</h2>
<%= form_for (book) do |f| %>
<% if book.errors.any? %>
<%= book.errors.count %> errors prohibited this book from being saved:
<% book.errors.full_messages.each do |message| %>
     <%= message %>
      <% end %>
<% end %>
<% end %>
<%= form_for (book) do |f| %>
   <h4>Title</h4>
   <%= f.text_field :title %>
   <h4>Opinion</h4>
   <%= f.text_area :body %>
   <br><%= f.submit 'Create Book', class: "btn btn-primary" %>
<% end %>

app/views/books/about.html.erb
<div class="container">
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>

app/views/books/edit.html.erb
<div class="container">
<div class="col-md-offset-4 col-md-6">
<h1>Editing Book</h1>
<%= form_for (@book) do |f| %>
<% if @book.errors.any? %>
<%= @book.errors.count %> errors prohibited this book from being saved:
<% @book.errors.full_messages.each do |message| %>
     <%= message %>
      <% end %>
<% end %>
<% end %>
<%= form_for(@book) do |f| %>
    <h4>Title:</h4>
    <%= f.text_field :title %>
    <h4>Body:</h4>
    <%= f.text_area :body %>
    <br><%= f.submit 'Update Book', class: "btn btn-primary" %>
    <br><%= link_to "Show", book_path(@book) %>
        <%= link_to "Back", books_path %>
<% end %>
</div>
</div>

app/views/books/home.html.erb
<p id="notice">
 <%=  flash[:notice] %>
</p>

<div class="message col-md-offset-4 col-md-6">
<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers  !!</h1>
<h5>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</h5>

<h5>you can share and exchange your opinions , inpressions , and emotions<br><br>
about various books!</h5>
</div>
<%= link_to "Log in", new_user_session_path, class:"btn btn-info col-xs-offset-4 col-xs-3" %><br>
<%= link_to "Sign up", new_user_registration_path, class:"btn btn-success col-xs-3 col-xs-offset-4" %>

app/views/books/index.html.erb
 <div class="container">
  <div class="row">
   <div class="col-xs-3">
    <%= render 'books/list', book: @book, user: @user %>
   </div>
   <div class="col-xs-9">
    <h3>Books</h3>
  <table class="table table-condensed">
   <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
   </thead>
   <tbody>
   <% @books.each do |book| %>
    <tr>
     <td>
      <%= link_to (attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:"50x50"), user_path(book.user) %>
     </td>
     <td>
     <%= link_to book.title, book_path(book) %>
     </td>
     <td>
     <%= book.body %>
     </td>
   </tr>
   <% end %>
  </tbody>
  </table>
  </div>
  </div>
 </div>

app/views/books/show.html.erb
<p id="notice">
 <%=  flash[:notice] %>
</p>

 <div class="container">
  <div class="row">
   <div class="col-xs-3">
    <%= render 'books/list', book: @book, user: @user %>
   </div>
   <div class="col-xs-9">
<h1>Book detail</h1>
  <table class="table table-condensed">
   <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td>
     <%= link_to user_path(@user) do %>
      <%= attachment_image_tag @books.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:"50x50" %>
      <%= @user.name %>
     <% end %>
    </td>
     <td>
     <%= @books.title %>
     </td>
     <td>
     <%= @books.body %>
     </td>
     <td>
     <% if @books.user == current_user %>
     <%= link_to "Edit", edit_book_path(@books), class:"btn btn-success" %>
     <% end %>
     <% if @books.user == current_user %>
     <%= link_to "Destroy", book_path(@books), class:"btn btn-danger",method: :delete, data: {confirm: "本当に消しますか？"} %>
     <% end %>
    </td>
   </tr>
  </tbody>
  </table>
  </div>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <header class="navber navber-fixed-top navber-inverse">
     <div class="container">
      <nav class="navber-left">
      <span>Bookers</span></nav>
      <nav>
      <ul class="navber-right">
    <% if user_signed_in? %>

        <%= link_to user_path(current_user), class: "my-bt" do%><i class="glyphicon glyphicon-home"></i> Home<% end %>

        <%= link_to users_path, class: "my-bt" do%><i class="glyphicon glyphicon-user"></i> Users<% end %>

        <%= link_to books_path, class: "my-bt" do%><i class="glyphicon glyphicon-book"></i> books<% end %>

        <%= link_to destroy_user_session_path, method: :delete, class: "my-bt" do%><i class="glyphicon glyphicon-log-out"></i> logout<% end %>

    <% else %>
        <%= link_to "http://localhost:3000", class: "my-bt" do%><i class="glyphicon glyphicon-home"></i> Home<% end %>

        <%= link_to "http://localhost:3000/home/about", class: "my-bt" do%><i class="glyphicon glyphicon-link"></i> About<% end %>

        <%= link_to new_user_registration_path, class: "my-bt" do%><i class="glyphicon glyphicon-edit"></i> sign up<% end %>

        <%= link_to new_user_session_path, class: "my-bt" do%><i class="glyphicon glyphicon-log-in"></i> login<% end %>

    <% end %>
    </ul>
    </nav>
  </div>
  </header>
  <%= yield %>
  <footer>
   <div class="col-xs-3 col-xs-offset-9">CopyRight Infratop.inc
   </div>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
<h2>User info</h2>
<%= form_for (@user) do |f| %>
<% if @user.errors.any? %>
<%= @user.errors.count %> errors prohibited this obj from being saved:
<% @user.errors.full_messages.each do |message| %>
     <%= message %>
      <% end %>
<% end %>
<% end %>
<%= form_for (@user) do |f| %>
<h5>Name</h5>
<%= f.text_field :name %>
<h5>Image</h5>

<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
<h5>Introduction</h5>
<%= f.text_field :introduction %><br>
<%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
  <div class="container">
  <div class="row">
   <div class="col-xs-3">
    <%= render 'books/list', book: @book, user: @user %>
   </div>
   <div class="col-xs-9">
   <h3>Users</h3>
   <table class="table table-condensed">
   <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
   </thead>
  <% @users.each do |users| %>
   <tbody>
    <tr>
     <td>
      <%= attachment_image_tag users, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:"50x50" %>
     </td>
     <td>
     <%= users.name %>
     </td>
     <td>
     <%= link_to "Show", user_path(users.id) %>
     </td>
    </tr>
   <% end %>
   </tbody>
   </table>
   </div>
  </div>
  </div>

app/views/users/show.html.erb
<%= flash[:success] %>
<p id="notice">
 <%=  flash[:notice] %>
</p>

   <div class="container">
  <div class="row">
   <div class="col-xs-3">
    <%= render 'books/list', book: @book, user: @users %>
   </div>
   <div class="col-xs-9">
<h3>Books</h3>
  <table class="table table-condensed">
   <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
   </thead>
   <tbody>
   <% @books.each do |book| %>
    <tr>
     <td>
     <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:"50x50" %>
     </td>
     <td>
     <%= link_to book.title, book_path(book) %>
     </td>
     <td>
     <%= book.body %>
     </td>
   </tr>
   <% end %>
  </tbody>
  </table>
  </div>
  </div>
 </div>